[Service]
# Keep custom state under /root for this image.
ExecStart=
ExecStart=/usr/sbin/tailscaled --state=/data/tailscale/tailscald.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS
