# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-variscite-test"
BBFILE_PATTERN_meta-variscite-test = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-variscite-test = "20"

LAYERDEPENDS_meta-variscite-test = "core"
LAYERSERIES_COMPAT_meta-variscite-test = "scarthgap"
